### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by Warcren** [lilferraro/android_device_samsung_trltespr#1]
I can't get GPS to lock on this rom. I've done a clean install of this rom and gotten a strong lock on stock before flashing but the problem persists. When using tools like GPS Locker the phone can't even seem to see any satellites. Let me know if i can provide any additional  information.

**Comment by lilferraro** [comment]
this issue is for the proprietary files.... Not device tree but duely noted sir. Im on pg1 firmware and gps works fine...

**Comment by Warcren** [comment]
Hello Lilferraro,

I went back to stock OK1 and upgraded phone via Sprint Updates to PJ1. I
got a strong lock then rooted and flashed LineageOS. Now on firmware PG1
and still getting 0/0 on satellites.

On May 28, 2017 12:49 PM, "lilferraro" <notifications@github.com> wrote:

this issue is for the proprietary files.... Not device tree but duely noted
sir. Im on pg1 firmware and gps works fine...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lilferraro/android_device_samsung_trltespr/issues/1#issuecomment-304526298>,
or mute the thread
